from pathlib import Path
from docx import Document

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "outputs"


def generate_docx(
        project_name: str,
        documentation_content: str) -> dict:
    """
    Generates a DOCX project documentation file.

    Args:
        project_name (str): Name of the project.
        documentation_content (str): Documentation generated by the Documentation Agent.

    Returns:
        str: Success message with the generated DOCX location.
    """

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    safe_project_name = (
        project_name
        .strip()
        .lower()
        .replace(" ", "_")
    )

    project_dir = OUTPUT_DIR / safe_project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    docx_path = project_dir / "Project_Documentation.docx"

    document = Document()

    document.add_heading(project_name, level=1)

    document.add_paragraph(documentation_content)
    
    try:
        document.save(docx_path)

    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

    return {
    "status": "success",
    "file_name": "Project_Documentation.docx",
    "directory": str(project_dir),
    "file_path": str(docx_path)
}