from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "outputs"

def generate_readme(
        project_name: str,
        documentation_content: str) -> dict:
    """
    Generates a README.md file for the specified project using the documentation content.

    Args:
        project_name (str): The name of the project.
        documentation_content (str): The documentation generated by the Documentation Agent.

    Returns:
        str: Success message with the file location.
    """

    # Create outputs directory if it doesn't exist
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    safe_project_name = (
        project_name
        .strip()
        .lower()
        .replace(" ", "_")
    )

    # Create project folder inside outputs
    project_dir = OUTPUT_DIR / safe_project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    # README file path
    readme_path = project_dir / "README.md"

    # Write documentation to README
    try:
        with open(readme_path, "w", encoding="utf-8") as file:
            file.write(documentation_content)
            
    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }
    return {
    "status": "success",
    "file_name": "README.md",
    "directory": str(project_dir),
    "file_path": str(readme_path)
}

